### ISSUE TITLE
query: status of this work?

### ISSUE THREAD

**Issue by ha0ye** [ocbe-uio/RCFF#13]
With the public announcements of CFF and adoption by Zenodo, I'm wondering what the status of this project is, and if you have a roadmap for features?

**Comment by dpprdan** [comment]
ICYMI https://twitter.com/stdruskat/status/1420134981041627143

**Comment by wleoncio** [comment]
Hi, and thank you for the interest in this project!

This is a package I am quite interested in, but progress has been slow due to it being very low in priority when compared to the internal software I'm developing here at OCBE (basically half of the [ocbe-uio](https://github.com/orgs/ocbe-uio/repositories) repositories). Things aren't looking too bright for the rest of the year either, as I've got another round of parental leave coming up soon.

As for a roadmap, I have an [MVP milestone](https://github.com/ocbe-uio/RCFF/milestone/1) setup with the set of minimum features that should be implemented for release 1.0.0. Any help get those issues solved is welcome!
